//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;

    public partial class Artikl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikl()
        {
            this.Dostupnost = new HashSet<Dostupnost>();
            this.Kompatibilnost = new HashSet<Kompatibilnost>();
            this.Kompatibilnost1 = new HashSet<Kompatibilnost>();
            this.StavkaDokumenta = new HashSet<StavkaDokumenta>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string Kratki_opis { get; set; }
        public string Specifikacija { get; set; }
        public double Cijena { get; set; }
        public int Vrsta_ID { get; set; }
    
        public virtual TipZaposlenika VrstaArtikla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostupnost> Dostupnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kompatibilnost> Kompatibilnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kompatibilnost> Kompatibilnost1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaDokumenta> StavkaDokumenta { get; set; }

        public static BindingList<Artikl> DohvatiSveArtikle()
        {
            BindingList<Artikl> artikli = null;
            
            using (TechStoreEntities db = new TechStoreEntities())
            {
                artikli = new BindingList<Artikl>(db.Artikl.ToList());
            }

            return artikli;
        }

        public static List<Artikl> DohvatiKomponente(string upit)
        {
            List<Artikl> komponente = null;
            using (TechStoreEntities db = new TechStoreEntities())
            {
                komponente = db.Artikl.SqlQuery(upit).ToList();
            }

            return komponente;
        }

        public override string ToString()
        {
            return Naziv;
        }
    }
}
