//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompatibilnost
    {
        public int Komponenta1 { get; set; }
        public int Komponenta2 { get; set; }
        public bool Kompatibilni { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Artikl Artikl1 { get; set; }
    }
}
